# Generated by Django 2.2.7 on 2019-12-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspicious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AC_NO', models.CharField(max_length=15)),
                ('ac_name', models.CharField(max_length=200)),
                ('AC_BRANCH', models.CharField(max_length=4)),
                ('AC_CCY', models.CharField(max_length=4)),
                ('FCY_AMOUNT', models.IntegerField(null=True)),
                ('LCY_AMOUNT', models.IntegerField()),
                ('VALUE_DT', models.CharField(blank=True, max_length=10)),
                ('AC_STAT_NO_DR', models.CharField(max_length=2)),
                ('ACCOUNT_CLASS', models.CharField(max_length=10)),
                ('ACY_AVL_BAL', models.IntegerField(null=True)),
                ('RECORD_STAT', models.CharField(max_length=1)),
                ('CUST_NO', models.IntegerField()),
                ('min_balance', models.IntegerField(null=True)),
                ('TotalTnx', models.IntegerField(null=True)),
                ('serviceDesc', models.CharField(default='none', max_length=100)),
                ('OnboardDate', models.CharField(max_length=20, null=True)),
                ('msisdn', models.CharField(max_length=18, null=True)),
                ('eAlertTelPhone', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('TRUE POSITIVE', 'TRUE POSITIVE'), ('FALSE POSITIVE', 'FALSE POSITIVE'), ('UNDEFINED', 'UNDEFINED')], default='UNDEFINED', max_length=20)),
                ('comment', models.TextField(blank=True, max_length=25)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
