# Generated by Django 2.2.7 on 2019-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicious',
            name='comment',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
